### ISSUE TITLE
ABORT: ASSERTION FAILED: bsp != *bspp (expire_bare_shunts() +3664 programs/pluto/kernel.c)

### ISSUE THREAD

**Issue by AnatoliChe** [libreswan/libreswan#550] opened 2021-11-18 13:45 UTC
I have restart my libreswan when I have problem with one of channel.
It won't be a problem but I have 10+ channels and all of them are restarted constantly with problem with only one.
Could you give me advice who to avoid restart of all channels with problem with one of them?
I have log:
`
Nov 18 14:43:12.088246: "peerl-peerdpt2" #2: the peer proposed: 192.168.78.194/32 -<all>-> 192.168.78.1/32
Nov 18 14:43:12.090857: "peerl-peerdpt2" #45: responding to Quick Mode proposal {msgid:3a5385ef}
Nov 18 14:43:12.090869: "peerl-peerdpt2" #45:     us: 192.168.78.194<192.168.78.194>[@peerl2.ipsec.tkb]  them: 192.168.78.1<192.168.78.1>[@peerdpt-datagroup.ipsec.tkb]
Nov 18 14:43:12.091141: "peerl-peerdpt2" #45: sent Quick Mode reply, inbound IPsec SA installed, expecting confirmation transport mode {ESP=>0x38bcfd63 <0xbf0b6cd6 xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=none NATD=none DPD=active}
Nov 18 14:43:12.127132: "peerl-peerdpt2" #45: IPsec SA established transport mode {ESP=>0x38bcfd63 <0xbf0b6cd6 xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=none NATD=none DPD=active}
`

ok ipsec established

ok one link is down
`
Nov 18 14:47:44.641232: netlink_acquire got message with length 68 < 232 bytes; ignore message
Nov 18 14:47:49.414758: netlink_acquire got message with length 68 < 232 bytes; ignore message
Nov 18 14:48:43.795905: "peerl-peerdpt2" #5: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:48:45.756352: netlink_acquire got message with length 68 < 232 bytes; ignore message
`

still looking ok
`
Nov 18 14:49:43.848976: "peerl-peerdpt2" #5: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:49:49.417946: netlink_acquire got message with length 68 < 232 bytes; ignore message
Nov 18 14:50:13.848948: "peerl-peerdpt2" #5: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:50:32.105566: "peerl-peerdpt2" #43: deleting state (STATE_QUICK_R2) aged 1200.112375s and sending notification
Nov 18 14:50:32.105640: "peerl-peerdpt2" #43: ESP traffic information: in=64MB out=7MB
Nov 18 14:50:33.848983: "peerl-peerdpt2" #5: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:50:42.172228: "peerl-peerdpt2" #5: DPD action - restarting all connections that share this peer
Nov 18 14:50:42.172253: "peerl-peerdpt2": terminating SAs using this connection
Nov 18 14:50:42.172266: "peerl-peerdpt2" #45: deleting state (STATE_QUICK_R2) aged 450.083996s and sending notification
Nov 18 14:50:42.172318: "peerl-peerdpt2" #45: ESP traffic information: in=10MB out=1MB
Nov 18 14:50:42.176066: "peerl-peerdpt2" #5: deleting state (STATE_MAIN_R3) aged 16685.839554s and sending notification
Nov 18 14:50:42.176222: "peerl-peerdpt2" #2: deleting state (STATE_MAIN_I4) aged 16686.322442s and sending notification
Nov 18 14:50:42.176339: "peerl-peerdpt2" #47: initiating IKEv1 Main Mode connection
Nov 18 14:50:42.176401: "peerl-peerdpt2" #47: sent Main Mode request
Nov 18 14:50:42.673932: "peerl-peerdpt2" #47: STATE_MAIN_I1: retransmission; will wait 0.5 seconds for response
Nov 18 14:50:43.174478: "peerl-peerdpt2" #47: STATE_MAIN_I1: retransmission; will wait 1 seconds for response
Nov 18 14:50:43.849011: "peerl-peerdpt2" #47: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:50:43.849032: "peerl-peerdpt2" #47: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:50:43.849051: "peerl-peerdpt2" #47: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:50:44.173397: "peerl-peerdpt2" #47: STATE_MAIN_I1: retransmission; will wait 2 seconds for response
Nov 18 14:50:46.175465: "peerl-peerdpt2" #47: STATE_MAIN_I1: retransmission; will wait 4 seconds for response
Nov 18 14:50:47.208944: "peerl-peerdpt2" #47: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:50:47.208967: "peerl-peerdpt2" #47: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:50:49.419848: netlink_acquire got message with length 68 < 232 bytes; ignore message
Nov 18 14:50:50.174658: "peerl-peerdpt2" #47: STATE_MAIN_I1: retransmission; will wait 8 seconds for response
Nov 18 14:50:50.805793: "peerl-peerdpt2": assign_holdpass() no bare shunt to remove? - mismatch?
Nov 18 14:50:50.805805: initiate on demand by acquire from 192.168.78.194:0 to 192.168.78.1:0 proto=GRE
Nov 18 14:50:53.208945: "peerl-peerdpt2" #47: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:50:58.175249: "peerl-peerdpt2" #47: STATE_MAIN_I1: retransmission; will wait 16 seconds for response
Nov 18 14:51:01.208963: "peerl-peerdpt2" #47: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:51:14.185562: "peerl-peerdpt2" #47: STATE_MAIN_I1: retransmission; will wait 32 seconds for response
Nov 18 14:51:17.235620: "peerl-peerdpt2" #47: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:51:20.806408: CONFLICTING existing bare shunt 0x557a1c062d80 192.168.78.194/32:0 --47--> 192.168.78.1/32:0 => %hold 0    acquire
Nov 18 14:51:20.806437: CONFLICTING      new bare shunt 0x557a1c03aba0 192.168.78.194/32:0 --47--> 192.168.78.1/32:0 => %hold 0    acquire
Nov 18 14:51:20.806445: "peerl-peerdpt2": assign_holdpass() no bare shunt to remove? - mismatch?
Nov 18 14:51:20.806459: initiate on demand by acquire from 192.168.78.194:0 to 192.168.78.1:0 proto=GRE
Nov 18 14:51:46.195554: "peerl-peerdpt2" #47: STATE_MAIN_I1: 60 second timeout exceeded after 7 retransmits.  No response (or no acceptable response) to our first IKEv1 message
Nov 18 14:51:46.195578: "peerl-peerdpt2" #47: starting keying attempt 2 of an unlimited number
Nov 18 14:51:46.195625: "peerl-peerdpt2" #48: initiating IKEv1 Main Mode connection to replace #47
Nov 18 14:51:46.195724: "peerl-peerdpt2" #48: sent Main Mode request, replacing #47
Nov 18 14:51:46.195731: "peerl-peerdpt2" #47: deleting state (STATE_MAIN_I1) aged 64.019401s and NOT sending notification
Nov 18 14:51:46.195738: "peerl-peerdpt2" #47: deleting IKE SA but connection is supposed to remain up; schedule EVENT_REVIVE_CONNS
Nov 18 14:51:46.195752: "peerl-peerdpt2": initiating connection 'peerl-peerdpt2' with serial $2 which received a Delete/Notify but must remain up per local policy
`

No it's a little bit strange (for me)

`
Nov 18 14:51:50.198890: "peerl-peerdpt2" #48: STATE_MAIN_I1: retransmission; will wait 4 seconds for response
Nov 18 14:51:50.806933: CONFLICTING existing bare shunt 0x557a1c03aba0 192.168.78.194/32:0 --47--> 192.168.78.1/32:0 => %hold 0    acquire
Nov 18 14:51:50.806958: CONFLICTING      new bare shunt 0x557a1c04efc0 192.168.78.194/32:0 --47--> 192.168.78.1/32:0 => %hold 0    acquire
Nov 18 14:51:50.806966: "peerl-peerdpt2": assign_holdpass() no bare shunt to remove? - mismatch?
Nov 18 14:51:50.806975: initiate on demand by acquire from 192.168.78.194:0 to 192.168.78.1:0 proto=GRE
Nov 18 14:51:53.235606: "peerl-peerdpt2" #48: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:51:54.200621: "peerl-peerdpt2" #48: STATE_MAIN_I1: retransmission; will wait 8 seconds for response
Nov 18 14:51:57.235624: "peerl-peerdpt2" #48: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:52:02.202227: "peerl-peerdpt2" #48: STATE_MAIN_I1: retransmission; will wait 16 seconds for response
Nov 18 14:52:05.235614: "peerl-peerdpt2" #48: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 14:52:18.205270: "peerl-peerdpt2" #48: STATE_MAIN_I1: retransmission; will wait 32 seconds for response
Nov 18 14:52:20.807600: CONFLICTING existing bare shunt 0x557a1c04efc0 192.168.78.194/32:0 --47--> 192.168.78.1/32:0 => %hold 0    acquire
Nov 18 14:52:20.807624: CONFLICTING      new bare shunt 0x557a1c087160 192.168.78.194/32:0 --47--> 192.168.78.1/32:0 => %hold 0    acquire
Nov 18 14:52:20.807632: "peerl-peerdpt2": assign_holdpass() no bare shunt to remove? - mismatch?
`

first channel is still alive

`
Nov 18 15:00:11.868842: "peerl-peerdpt2" #56: STATE_MAIN_I1: retransmission; will wait 32 seconds for response
Nov 18 15:00:14.858826: "peerl-peerdpt2": initiating connection 'peerl-peerdpt2' with serial $2 which received a Delete/Notify but must remain up per local policy
Nov 18 15:00:14.915553: "peerl-peerdpt2" #56: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 15:00:18.448878: "peerl-peerdpt" #57: initiating Quick Mode IKEv1+RSASIG+ENCRYPT+PFS+UP+IKE_FRAG_ALLOW+ESN_NO to replace #46 {using isakmp#1 msgid:06e8a5ad proposal=AES_CBC-HMAC_SHA1_96 pfsgroup=MODP2048}
Nov 18 15:00:18.450385: "peerl-peerdpt" #57: sent Quick Mode request, to replace #46
Nov 18 15:00:18.467018: "peerl-peerdpt" #57: IPsec SA established transport mode {ESP=>0xc4cab617 <0x23a63b8a xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=none NATD=none DPD=active}
Nov 18 15:00:20.817309: CONFLICTING existing bare shunt 0x557a1c086f40 192.168.78.194/32:0 --47--> 192.168.78.1/32:0 => %hold 0    acquire
Nov 18 15:00:20.817345: CONFLICTING      new bare shunt 0x557a1c07f400 192.168.78.194/32:0 --47--> 192.168.78.1/32:0 => %hold 0    acquire
Nov 18 15:00:20.817352: "peerl-peerdpt2": assign_holdpass() no bare shunt to remove? - mismatch?
Nov 18 15:00:20.817357: initiate on demand by acquire from 192.168.78.194:0 to 192.168.78.1:0 proto=GRE
`

still have problem with one of channel
`
Nov 18 15:05:42.892262: "peerl-peerdpt2" #63: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 15:05:42.892278: "peerl-peerdpt2" #63: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 15:05:43.847265: "peerl-peerdpt2" #63: STATE_MAIN_I1: retransmission; will wait 4 seconds for response
Nov 18 15:05:46.888871: "peerl-peerdpt2" #63: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
Nov 18 15:05:47.846898: "peerl-peerdpt2" #63: STATE_MAIN_I1: retransmission; will wait 8 seconds for response
Nov 18 15:05:50.823639: CONFLICTING existing bare shunt 0x557a1c091a20 192.168.78.194/32:0 --47--> 192.168.78.1/32:0 => %hold 0    acquire
Nov 18 15:05:50.823665: CONFLICTING      new bare shunt 0x557a1c072d40 192.168.78.194/32:0 --47--> 192.168.78.1/32:0 => %hold 0    acquire
Nov 18 15:05:50.823673: "peerl-peerdpt2": assign_holdpass() no bare shunt to remove? - mismatch?
Nov 18 15:05:50.823678: initiate on demand by acquire from 192.168.78.194:0 to 192.168.78.1:0 proto=GRE
Nov 18 15:05:50.888848: "peerl-peerdpt2" #63: ERROR: asynchronous network error report on eth2 (192.168.78.194:500), complainant 192.168.78.194: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]
`
and finally
`
Nov 18 15:05:55.842183: ABORT: ASSERTION FAILED: bsp != *bspp (expire_bare_shunts() +3664 programs/pluto/kernel.c)
`

and restart libreswan ((((
Could you  help please

**Comment by cagney** [comment] 2021-11-18 17:02
Which version of libreswan?  Would you be able to try mainline?

**Comment by AnatoliChe** [comment] 2021-11-18 17:40
sorry it's quite old one
Libreswan 4.5 git clone from Jul 27 2021

Last I tried was v4.6 (unreleased) from 2021 Sep 29 and it was there.

**Comment by cagney** [comment] 2021-11-18 18:03
> sorry it's quite old one Libreswan 4.5 git clone from Jul 27 2021
> Last I tried was v4.6 (unreleased) from 2021 Sep 29 and it was there.

Ah, I could see it wasn't 4.5.

> I can see today's commits in kernel.c related with shunt and commit from 13 Nov. So I guess I'd try fresh LS.

Thanks.

**Comment by AnatoliChe** [comment] 2021-11-22 07:25
Compiled it 2021-11-19
* main 3489b22fe5 kerne: move raw_policy({src,dst}_host) parameters to struct kernel_encap parameter

Down links and have:

`
Nov 20 21:07:21.452345: "peerl-peerdpt2": assign_holdpass() no bare shunt to remove? - mismatch?
Nov 20 21:07:26.929765: ERROR: kernel: xfrm XFRM_MSG_DELPOLICY%pass(none) response for flow (out): No such file or directory (errno 2)
Nov 20 21:07:26.929780: delete kernel shunt 192.168.43.194/32:0 -GRE-> 192.168.43.1/32:0 failed - deleting from pluto shunt table
Nov 20 21:07:26.929788: failed to delete bare shunt
Nov 20 21:07:26.929795: ABORT: ASSERTION FAILED: bsp != *bspp (expire_bare_shunts() +3813 programs/pluto/kernel.c)

Nov 20 21:07:36.986616: FIPS Mode: NO
Nov 20 21:07:36.986632: NSS crypto library initialized
Nov 20 21:07:36.986680: FIPS mode disabled for pluto daemon
Nov 20 21:07:36.986684: FIPS HMAC integrity support [disabled]
Nov 20 21:07:36.986784: libcap-ng support [enabled]
Nov 20 21:07:36.986788: Linux audit support [disabled]
Nov 20 21:07:36.986791: Starting Pluto (Libreswan Version 4.6 IKEv2 IKEv1 XFRM XFRMI esp-hw-offload FORK PTHREAD_SETSCHEDPRIO NSS (IPsec profile) (native-PRF) DNSSEC LIBCAP_NG AUTH_PAM NETWORKMANAGER CURL(non-NSS)) pid:12703
`

("No such file or directory" is interesting what file it cannot find...)

**Comment by cagney** [comment] 2021-11-23 21:39
> ("No such file or directory" is interesting what file it cannot find...)

It can't find the `ip xfrm policy` that either:
- the kernel, when the acquire happened; or
- pluto when modifying the policy

inserted earlier; I suspect the former.

Looking at the original logs, I extracted:
```
the peer proposed: 192.168.78.194/32 -<all>-> 192.168.78.1/32
15:00:20.817357: initiate on demand by acquire from 192.168.78.194:0 to 192.168.78.1:0 proto=GRE
15:05:50.823639: CONFLICTING existing bare shunt 0x557a1c091a20 192.168.78.194/32:0 --47--> 192.168.78.1/32:0 => %hold 0 acquire
15:05:50.823665: CONFLICTING new bare shunt 0x557a1c072d40 192.168.78.194/32:0 --47--> 192.168.78.1/32:0 => %hold 0 acquire
15:05:50.823678: initiate on demand by acquire from 192.168.78.194:0 to 192.168.78.1:0 proto=GRE
[[HERE]]
15:05:55.842183: ABORT: ASSERTION FAILED: bsp != *bspp (expire_bare_shunts() +3664 programs/pluto/kernel.c)
```
Where I put [[HERE]] I suspect the new stuff was happening, it's just it wasn't being reported (for instance, DELPOLICY errors were being supressed).  So a guess is:
- acquire tries to negotiate 192.168.78.194:0 to 192.168.78.1:0 proto=GRE; fails but leaves bare shunt
- acquire tries to negotiate 192.168.78.194:0 to 192.168.78.1:0 proto=GRE and encounters existing shunt which digs a hole

**Comment by cagney** [comment] 2021-11-23 21:43
BTW, any chance of switching to IKEv2; I don't expect it to fix the specific issue but it will help with being a more familiar protocol

**Comment by letoams** [comment] 2021-11-24 15:42
On Wed, 24 Nov 2021, AnatoliChe wrote:

> Nov 23 15:05:04.312345: CONFLICTING existing bare shunt 0x55b8fbdc82d0 192.168.43.194/32:0 -GRE-> 192.168.43.1/32:0 => HOLD
> 0 acquire
> 
> Nov 23 15:05:04.312388: CONFLICTING new bare shunt 0x55b8fbdc8360 192.168.43.194/32:0 -GRE-> 192.168.43.1/32:0 => HOLD 0
> acquire
> 
> Nov 23 15:05:04.312395: "peerl-peerdpt": assign_holdpass() no bare shunt to remove? - mismatch?
> 
> Nov 23 15:05:04.312400: initiate on demand by acquire from 192.168.43.194:0 to 192.168.43.1:0 proto=GRE

I am still puzzled how you were responding to IKE and hitting
acquire/initiating code path....

> Nov 23 15:05:11.306025: "peerl-peerdpt" #1959: STATE_MAIN_I1: retransmission; will wait 32 seconds for response
> 
> Nov 23 15:05:19.281029: ERROR: kernel: xfrm XFRM_MSG_DELPOLICY%pass(none) response for flow (out): No such file or
> directory (errno 2)

Note the error is somewhat confusing (because of limited POSIX errors
possible). It is not a real file or directory but a kernel state that
is not there.

>       any chance of switching to IKEv2; I don't expect it to fix the specific issue but it will help with being a
>       more familiar protocol
>       Yes, but if your server have at least one ikev1 and link is down - you will have restart hole libreswan
>       Libreswan restarts fast enough to not drop calls/video and have only some stuck but it's a bomb.
> 
> Is it possible change

That would help.

> passert(bsp != *bspp);
> to someting like
> llog(RC_LOG_SERIOUS, logger,"bsp != *bspp");
> delete_state(dst);
> ?
> maybe it's better then kill whole daemon with all SA without cleanup ip xfrm ??? ('cause daemon is dead but we have a lot
> ip xfrm policy?)

You can do that, but with mixed up pluto - kernel state, confusion will
just spread and I don't think you'd survive much longer.

Note libreswan on restart (after a crash) clears all XFRM policy/state
precisely for this case - to remove remnants from previous processes.

Paul

**Comment by AnatoliChe** [comment] 2021-11-24 18:33
> I am still puzzled how you were responding to IKE and hitting
acquire/initiating code path....

#ulimit -c unlimited
wait when link down, passert has to generate core dump
maybe backtrace can clarify what is going on

**Comment by cagney** [comment] 2022-04-07 18:52
> Nov 23 15:05:19.281029: ERROR: kernel: xfrm XFRM_MSG_DELPOLICY%pass(none) response for flow (out): No such file or directory (errno 2)

Just FYI, this log line should be fixed.  The "No such file or directory" was referring to kernel policy (aka ip xfrm policy).
We're still puzzled by the pexpect.

**Comment by cagney** [comment] 2022-04-12 20:25
In `expire_bare_shunts()` the code is walking the bare shunts table at the same time as the list is being updated.  It uses the code:
```
	for (struct bare_shunt **bspp = &bare_shunts; *bspp != NULL; ) {
		struct bare_shunt *bsp = *bspp;
		if (age > deltasecs(pluto_shunt_lifetime) || all) {
			if (!delete_bare_shunt()) {
				llog(RC_LOG_SERIOUS, logger,
					    "failed to delete bare shunt");
			}
			passert(bsp != *bspp);
		} else {
			bspp = &bsp->next;
		}
	}
```
the problem is with how delete_bare_shunt() used.  The function is expected to, behind the scene, delete the target of and then update the value of the `*bspp` pointer (aka `bsp`).  Hence the non-obvious expectation that `bsp != *bspp`.

**Comment by cagney** [comment] 2022-04-12 21:41
In `delete_bare_shunt()` the code:
```
	struct bare_shunt **bs_pp = bare_shunt_ptr(&src, &dst, why);
	if (bs_pp == NULL) {
		return ok;
	}
	free_bare_shunt(bs_pp);
```
is executed unconditionally.  Since the passert() fired, the above call to `bare_shunt_ptr()` some how found the wrong shunt (and then deleted it, or there's an alias bug but I've my doubts).

Way forward is to pass `bspp` into `delete_bare_shunt()` so that there's no possible mistake.

**Comment by cagney** [comment] 2022-04-13 15:13
The passert is gone, and the correct bare shunt entry is deleted.

**Closed** 2022-04-13 15:23 UTC
