### ISSUE TITLE
Two Win10 computer behind same NAT: only one works

### ISSUE THREAD

**Issue by Loginbug** [libreswan/libreswan#322] opened 2020-03-29 10:32 UTC
I have two windows 10 clients behind the same home NAT.
They have different users and passwords.
One works, second not. 
NOT CONCURRENT CONNECTION CASE
Can't understand why.
xl2tp/Libreswan 3.29 at Debian 10 VPS server.
Setup made with https://github.com/hwdsl2/setup-ipsec-vpn

DEBUG LOG OF PROBLEMATIC CLIENT:
https://pastebin.com/V3uYXFky

Thanks for any help

**Comment by letoams** [comment] 2020-03-29 23:14
please try 3.30 as one issue with usernames getting the same lease IP
instead of different ones was fixed in that release?

Paul

**Comment by bleve** [comment] 2020-03-30 06:06
And if you are doing l2tp-over-ipsec - then this is expected behaviour. Because l2tp-over-ipsec is using transport mode and there can only be one client behind nat with transport mode.

Use ikev2.

**Comment by Loginbug** [comment] 2020-03-30 11:22
Just compiled libreswan 3.31.
Nothing changed.
New log here
https://pastebin.com/9KRNXBtv

@bleve i have read a lot about this problem. 
I'm NOT using two pcs behind the same NAT at SAME TIME. 
Anyway i have put this problematic pc under ANOTHER network (and another NAT). No changes.

**Comment by lucize** [comment] 2020-04-19 23:43
I think this problem was solved by iptables-mod-conntrack-extra at least on openwrt, depends on your  gateway

**Comment by letoams** [comment] 2021-04-05 15:04
Migrate any IKEv1 L2TP/IPsec with Transport Mode connection to a more modern IKEv2 configuration that uses Tunnel Mode. Than there will ne no problems with multiple clients behind the same NAT

**Closed by letoams** 2021-04-05 15:04 UTC
