### ISSUE TITLE
kernel_add_sa() failure as initiator stampedes into creating a tunnel per failed attempt plus retry

### ISSUE THREAD

**Issue by paulwouters** [libreswan/libreswan#1602] opened 2024-02-08 02:22 UTC
When as initiator you receive IKE_AUTH and all is good and you call add_sa() via a call chain of connection_establish_child(),
and there is a problem (eg add_sa fails because you do packet offload with attempted nat-encapsulation via forced encapsulation=yes on transport=yes SA), the code path returns v2N_INVALID_SYNTAX.

This causes the existing IKE and Child SA to remain in a weird state, while a fresh new one is created.

The results are:
```
000 Total IPsec connections: loaded 6, active 1
000  
000 State Information: DDoS cookies not required, Accepting new IKE connections
000 IKE SAs: total(103), half-open(0), open(0), authenticated(103), anonymous(0)
000 IPsec SAs: total(103), authenticated(103), anonymous(0)
000  
000 #8: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA (established IKE SA); REKEY in 6270s; idle;
000 #10: "bofh":4500 STATE_V2_ESTABLISHED_CHILD_SA (IPsec SA established); REKEY in 6957s; isakmp#8; idle;
000 #10: "bofh" esp.7e43a65c@10.0.1.2 esp.ba9ac489@193.110.157.194 Traffic: ESPin=0B ESPout=0B ESPmax=0B 
000 #11: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA (established IKE SA); REKEY in 6957s; idle;
000 #12: "bofh":4500 STATE_V2_ESTABLISHED_CHILD_SA (IPsec SA established); REKEY in 6957s; isakmp#11; idle;
000 #12: "bofh" esp.7cb871a3@10.0.1.2 esp.f2ea8644@193.110.157.194 Traffic: ESPin=0B ESPout=0B ESPmax=0B 
000 #13: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA (established IKE SA); REKEY in 6962s; idle;
000 #14: "bofh":4500 STATE_V2_ESTABLISHED_CHILD_SA (IPsec SA established); REKEY in 6962s; isakmp#13; idle;
000 #14: "bofh" esp.b093030a@10.0.1.2 esp.efb17a60@193.110.157.194 Traffic: ESPin=0B ESPout=0B ESPmax=0B 
000 #15: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA (established IKE SA); REKEY in 6972s; idle;
000 #16: "bofh":4500 STATE_V2_ESTABLISHED_CHILD_SA (IPsec SA established); REKEY in 6972s; isakmp#15; idle;
000 #16: "bofh" esp.2f0f0212@10.0.1.2 esp.2a66bbf1@193.110.157.194 Traffic: ESPin=0B ESPout=0B ESPmax=0B 
000 #17: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA (established IKE SA); REKEY in 6987s; idle;
000 #18: "bofh":4500 STATE_V2_ESTABLISHED_CHILD_SA (IPsec SA established); REKEY in 6987s; isakmp#17; idle;
000 #18: "bofh" esp.820ec37a@10.0.1.2 esp.31c00f7b@193.110.157.194 Traffic: ESPin=0B ESPout=0B ESPmax=0B 
000 #19: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA (established IKE SA); REKEY in 7007s; idle;
000 #20: "bofh":4500 STATE_V2_ESTABLISHED_CHILD_SA (IPsec SA established); REKEY in 7007s; isakmp#19; idle;
000 #20: "bofh" esp.1ae696e3@10.0.1.2 esp.2cc0f858@193.110.157.194 Traffic: ESPin=0B ESPout=0B ESPmax=0B 
[...]
```

Changing the related code to return another notify that is not considered "fatal", eg v2N_TEMPORARY_FAILURE,
causes the child remnant to be removed, and keeps the childless IKE SA around. While this appears better, there
is now no more shunt in place, and we leak in cleartext.

maybe zap_child() needs to be called before returning v2N_TEMPORARY_FAILURE (or another notify?)

**Comment by cagney** [comment] 2024-02-09 03:03
This sounds like `impair-install-ipsec-sa-outbound-state-initiator-ikev2`:
```
"west-east" #1: initiating IKEv2 connection to 192.1.2.23 using UDP
"west-east" #1: sent IKE_SA_INIT request to 192.1.2.23:UDP/500
"west-east" #1: sent IKE_AUTH request to 192.1.2.23:UDP/500 {cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=DH19}
"west-east" #1: initiator established IKE SA; authenticated peer using authby=secret and ID_FQDN '@east'
"west-east" #2: IMPAIR: kernel: install_ipsec_sa_outbound_state in setup_half_kernel_state()
"west-east" #2: CHILD SA encountered fatal error: INVALID_SYNTAX
"west-east" #1: encountered fatal error in state STATE_V2_ESTABLISHED_IKE_SA
"west-east" #2: connection is supposed to remain up; revival attempt 1 scheduled in 0 seconds
"west-east" #2: IMPAIR: revival: skip scheduling revival event
ERROR: "west-east" #2: netlink response for Del SA esp.ESPSPIi@192.1.2.23: No such process (errno 3)
"west-east" #1: deleting IKE SA (ESTABLISHED_IKE_SA) and NOT sending notification
```

**Comment by cagney** [comment] 2024-02-09 14:48
btw, just to double check, are these on the responder?
```
000 #8: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA (established IKE SA); REKEY in 6270s; idle;
000 #10: "bofh":4500 STATE_V2_ESTABLISHED_CHILD_SA (IPsec SA established); REKEY in 6957s; isakmp#8; idle;
```

**Comment by cagney** [comment] 2024-02-09 17:08
Is the initiator backing off?  The test:
```
"west-east" #2: IMPAIR: revival: skip scheduling revival event
```
so that it can confirm the blocking shunt is installed during revival; but that means it can't check revival is backing off.

**Comment by paulwouters** [comment] 2024-02-09 18:53
it depends on the code. The original code returns v2N_INVALID_SYNTAX which is caught in v2_notification_fatal() which results in the IKE SA being killed, and the connection is then in a sort-of auto=add state?

on my machine, I changed the code to return v2N_TEMPORARY_FAILURE. Then we keep the IKE SA:

#357: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA (established IKE SA); REKEY in 27874s; REPLACE in 28538s; newest; idle;


but the child remains are gone and no proper routed policy (eg spd rules blocking traffic) are in place and we leak in the clear.

**Comment by cagney** [comment] 2024-02-09 23:37
the fatal case should look more like
```
"san" #1: initiating IKEv2 connection to 192.1.2.23 using UDP
"san" #1: sent IKE_SA_INIT request to 192.1.2.23:UDP/500
"san" #1: sent IKE_AUTH request to 192.1.2.23:UDP/500 {cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=DH19}
"san" #1: X509: authentication failed; peer certificate subjectAltName extension does not match ID_FQDN 'NOTeast.testing.libreswan.org'
"san" #1: deleting IKE SA (PARENT_I2) and sending notification
"san" #1: connection is supposed to remain up; revival attempt 1 scheduled in 0 seconds
```

**Comment by cagney** [comment] 2024-02-10 22:45
- [ ] #1615
- [ ] #1614

**Comment by cagney** [comment] 2024-02-12 16:13
Revival appears to be working, looking at the rekey times:
```
000 #11: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA; REKEY in 6957s; idle;
000 #12: "bofh":4500 STATE_V2_ESTABLISHED_CHILD_SA; REKEY in 6957s; isakmp#11; idle;
```
next is in 5s
```
000 #13: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA; REKEY in 6962s; idle;
000 #14: "bofh":4500 STATE_V2_ESTABLISHED_CHILD_SA; REKEY in 6962s; isakmp#13; idle;
```
next is in 10s
```
000 #15: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA; REKEY in 6972s; idle;
000 #16: "bofh":4500 STATE_V2_ESTABLISHED_CHILD_SA; REKEY in 6972s; isakmp#15; idle;
```
next is in 15s
```
000 #17: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA; REKEY in 6987s; idle;
000 #18: "bofh":4500 STATE_V2_ESTABLISHED_CHILD_SA; REKEY in 6987s; isakmp#17; idle;
```
next is in 20s
```
000 #19: "bofh":4500 STATE_V2_ESTABLISHED_IKE_SA; REKEY in 7007s; idle;
000 #20: "bofh":4500 STATE_V2_ESTABLISHED_CHILD_SA; REKEY in 7007s; isakmp#19; idle;
```

**Comment by cagney** [comment] 2024-02-12 16:28
Ignoring the question of what status should be returned:

> returns v2N_INVALID_SYNTAX which is caught in v2_notification_fatal() which results in the IKE SA being killed, and the connection is then in a sort-of auto=add state?

The IKE SA is dropped on the floor and then the connection tries to revive with 5s backoff.  Which is reasonable behaviour for INVALID_SYNTAX.

**Comment by letoams** [comment] 2024-02-12 16:43
On Mon, 12 Feb 2024, cagney wrote:

> Ignoring the question of what status should be returned:
>
>       returns v2N_INVALID_SYNTAX which is caught in v2_notification_fatal() which results in the IKE SA being killed, and the
>       connection is then in a sort-of auto=add state?
> 
> The IKE SA is dropped on the floor and then the connection tries to revive with 5s backoff. Which is reasonable behaviour for
> INVALID_SYNTAX.

Sure, which is why I think INVALID_SYNTAX is wrong. The IKE SA should
not be torn down. Which is why I looked at using TEMPORARY_FAILURE,
but as stated, that seems to not cause an unrouting even, thus losing
the shunt causing a leak. There is also no revival of the failed child
SA which would possibly have caused at least the negotiationshunt to
get installed again.

**Comment by cagney** [comment] 2024-02-12 17:35
The child sa, for this h/w is going to keep failing so, if anything, it should be marked as a permanent failure.

**Comment by letoams** [comment] 2024-02-12 18:33
On Mon, 12 Feb 2024, cagney wrote:

> The child sa, for this h/w is going to keep failing so, if anything, it should be marked as a permanent failure.

We don't actually know that. Eg it could be failing due to hitting max
hardware keys and if another tunnel goes down, this one could complete.

I don't know how we could tell the difference though :/

Also, the issue is really that we are mapping an internal failure onto
IKEv2 notify codes. If these code paths returned STF_INTERNAL_ERROR,
that would be more clear.

**Comment by cagney** [comment] 2024-02-12 18:49
STF_INTERNAL_ERROR needs to be deleted

**Comment by cagney** [comment] 2024-02-12 19:13
See #1614, revival of the IKE_AUTH Child SA has never worked.

**Comment by cagney** [comment] 2024-02-26 16:20
current behaviour of `impair-install-ipsec-sa-outbound-state-initiator-ikev2` is
```
"west-east" #1: initiating IKEv2 connection to 192.1.2.23 using UDP
"west-east" #1: sent IKE_SA_INIT request to 192.1.2.23:UDP/500
"west-east" #1: processed IKE_SA_INIT response from 192.1.2.23:UDP/500 {cipher=AES_GCM_16_256 integ=n/a prf=HMAC_SHA2_512 group=DH19}, initiating IKE_AUTH
"west-east" #1: sent IKE_AUTH request to 192.1.2.23:UDP/500
"west-east" #1: initiator established IKE SA; authenticated peer using authby=secret and ID_FQDN '@east'
"west-east" #2: IMPAIR: kernel: install_ipsec_sa_outbound_state in setup_half_kernel_state()
"west-east" #2: CHILD SA encountered fatal error: INVALID_SYNTAX
"west-east" #1: encountered fatal error in state STATE_V2_ESTABLISHED_IKE_SA
"west-east" #2: connection is supposed to remain up; revival attempt 1 scheduled in 0 seconds
"west-east" #2: IMPAIR: revival: skip scheduling revival event
ERROR: "west-east" #2: netlink response for Del SA esp.ESPSPIi@192.1.2.23: No such process (errno 3)
"west-east" #1: deleting IKE SA (ESTABLISHED_IKE_SA) and NOT sending notification
```
with
```
 ../../guestbin/ipsec-kernel-state.sh
src 192.0.1.254 dst 192.0.2.254
        proto esp spi 0x00000000 reqid 0 mode transport
        replay-window 0 
        sel src 192.0.1.254/32 dst 192.0.2.254/32 proto icmp type 8 code 0 dev eth1 
west #
 ../../guestbin/ipsec-kernel-policy.sh
src 192.0.1.0/24 dst 192.0.2.0/24
        dir out priority PRIORITY ptype main
        tmpl src 0.0.0.0 dst 0.0.0.0
                proto esp reqid 0 mode transport
```

**Comment by cagney** [comment] 2024-02-29 19:16
mainline should initiate the delete

**Comment by cagney** [comment] 2024-04-22 20:12
#1615 covers what is left of this bug

**Closed by cagney** 2024-04-22 20:12 UTC
Labels: v5.0rc1
