### ISSUE TITLE
No bare shunts after disabling IPSec on the other host

### ISSUE THREAD

**Issue by zoharfuchs** [libreswan/libreswan#268] opened 2019-08-21 01:36 UTC
I use libreswan-3.29-1.el7.x86_64 in AWS.
I have 3 nodes with Opporetunstic in between. Here is the config I'm using:

conn private
    auto=ondemand
    type=tunnel
    ikev2=insist
    authby=secret
    failureshunt=drop
    negotiationshunt=hold
    narrowing=yes
    dpddelay=1
    dpdtimeout=15
    dpdaction=restart
    retransmit-timeout=10s
    shuntlifetime=1m
    # left
    left=${IFACE}
    # right
    right=%opportunisticgroup

Since it is 3 nodes setup, we do have 2 tunnels on each node (trafficstatus). However, after we stop ipsec.service on of the nodes, from time to time, we don't have bare shunts on one of the nodes it does speak in clear mode with the stopped one. Though ipsec restart on the node will fix it and we will see bare shunts.

What could be the root cause of this inconsistency?

**Comment by letoams** [comment] 2020-01-28 19:54
the problem is when a host receives a delete from the remote. This could cause a new fresh %trap policy to not be installed, especially if you had /32 entries in the /etc/ipsec.d/policies/ file. This will be fixed in 3.30 (testing the fix now, hopefully out in a few days)

**Comment by cagney** [comment] 2023-11-22 15:14
5.0 should handle the established->on-demand (aka trap) transition correctly
if it proves to not be the case, please reopen

**Closed by cagney** 2023-11-22 15:14 UTC
Labels: v3.29
