### ISSUE TITLE
ERROR: netlink XFRM_MSG_UPDPOLICY response for flow eroute_connection add included errno 22: Invalid argument

### ISSUE THREAD

**Issue by rkujawa** [libreswan/libreswan#215] opened 2018-10-16 11:20 UTC
Hello. I'm trying to set up an IPv6 transport mode using libreswan 3.25 (as distributed with Fedora 28).

This is my config:
```
conn private
	type=transport
#      this parameter not supported anymore...
#	connaddrfamily=ipv6
        rightrsasigkey=%cert
        rightauth=rsasig
        right=%opportunisticgroup
        rightca=%same
        leftcert="NSS Certificate DB:myhostname"
        leftid=%fromcert
	left="2a02:4c80:10:64:5054:ff:feb9:675b"
        leftauth=rsasig
	negotiationshunt=hold
	failureshunt=drop
	ikev2=insist
	esp=aes256-sha2_512
	auto=ondemand
```

I have an appropriate group policy file:
```
$ cat /etc/ipsec.d/policies/private
2a02:4c80:10:64::/64
```

But when starting ipsec.service, I get the following errors:
```
Oct 16 13:05:44 oe-test1.test.c0ff33.net pluto[29313]: loading group "/etc/ipsec.d/policies/private"
Oct 16 13:05:44 oe-test1.test.c0ff33.net pluto[29313]: "private#2a02:4c80:10:64::/64": ERROR: netlink XFRM_MSG_UPDPOLICY response for flow eroute_connection add included errno 22: Invalid argument
```

The same configuration seems to be working with CentOS 7.5 (libreswan 3.23). Though there connaddrfamily parameter is uncommented. 

There seems to be some kind of problem with parsing the contents of policy file? Or libreswan inconrrectly assumes that the content should be IPv4 address? Any hints/ideas?

**Comment by letoams** [comment] 2018-10-17 05:00
On Tue, 16 Oct 2018, Radosław Kujawa wrote:

> Subject: [libreswan/libreswan] ERROR: netlink XFRM_MSG_UPDPOLICY response for
>     flow eroute_connection add included errno 22: Invalid argument (#215)

> Hello. I'm trying to set up an IPv6 transport mode using libreswan 3.25 (as distributed with Fedora 28).

> #      this parameter not supported anymore...
> #	connaddrfamily=ipv6

That sis obsoleted because it auto-detects this now based on the client
used.

> Oct 16 13:05:44 oe-test1.test.c0ff33.net pluto[29313]: loading group "/etc/ipsec.d/policies/private"
> Oct 16 13:05:44 oe-test1.test.c0ff33.net pluto[29313]: "private#2a02:4c80:10:64::/64": ERROR: netlink XFRM_MSG_UPDPOLICY response for fl
> ow eroute_connection add included errno 22: Invalid argument
> 
> The same configuration seems to be working with CentOS 7.5 (libreswan 3.23). Though there connaddrfamily parameter is uncommented.
> 
> There seems to be some kind of problem with parsing the contents of policy file? Or libreswan inconrrectly assumes that the content
> should be IPv4 address? Any hints/ideas?

I'll investigate. Thanks for letting us now.

Paul

**Comment by AdmiralNemo** [comment] 2019-11-10 02:01
This is still an issue in libreswan 3.27, which is included in RHEL 8.

**Comment by rnhmjoj** [comment] 2021-06-04 22:01
I'm still seeing the same error in 4.4 when specifying an IPv6 address in a policy file. Is IPv6 supposed to be supported?

**Comment by letoams** [comment] 2021-06-04 22:47
Are you intending to use opportunistic encryption? Nothing should prevent it from working but it has not been well tested. I will add test cases for it

**Comment by rnhmjoj** [comment] 2021-06-05 07:37
> Are you intending to use opportunistic encryption? Nothing should prevent it from working but it has not been well tested. I will add test cases for it

Yes, I just run `ipsec letsencrypt --client` and added a `/etc/ipsec.d/policies/private-or-clear` file with
```
0.0.0.0/0
::/0
```
This works, but only for IPv4: the `::/0` part is discarded with that error.

**Comment by rnhmjoj** [comment] 2021-09-04 15:05
The error is still there in libreswan 4.5. I've investigated a bit and policy groups (why are they called foodgroups?) can handle IPv6 just fine. So, the problem is not parsing but starting the connection. I also tested the `%group`, instead of `%opportunisticgroup` (used by the `letsencrypt` subcommand), and this seems to handle IPv6. So, the problem may be limited to the latter: it seems to assume IPv4 somethere. In fact, if I force IPv4 using `clientaddrfaimly=ipv6` I get a family mismatch error.

**Comment by cagney** [comment] 2022-04-07 19:02
Trying to add/update a kernel policy for transport mode where the inner and outer address families don't match can get "Invalid argument"

**Comment by letoams** [comment] 2022-04-07 19:16
What do you mean with inner and outer address with transport mode? This is not ipip so there is no inner/outer address and the families cannot be different.

Sent using a virtual keyboard on a phone

**Comment by cagney** [comment] 2022-04-07 19:29
If I were to try to insert something like:
```
src 2001:db8:0:1::/64 dst 2001:db8:0:2::/64 
        dir out priority PRIORITY ptype main 
        tmpl src 0.0.0.0 dst 0.0.0.0
                proto esp reqid 0 mode transport
```
where the inner client is IPv6 and the outer host is IPv4 say. then "Invalid argument" is returned.  See 66e218dfacc687a04532dd404fd560029dbb8e92 fixed an occurance of this bug in the teardown path.  We could easily have the same problem with OE when installing shunts.

**Comment by cagney** [comment] 2022-04-08 14:24
test is ikev2-oe-09-transport-ipv6

**Comment by cagney** [comment] 2022-04-08 17:16
I pushed a fix for the error:
```
ERROR: netlink XFRM_MSG_UPDPOLICY response for flow eroute_connection add included errno 22: Invalid argument
```
and updated ikev2-oe-09-transport-ipv6.  Just note that problems such as #683 still exist.

**Closed by cagney** 2022-04-08 17:16 UTC
Labels: kernel

**Comment by sob727** [comment] 2023-10-22 19:26
> I pushed a fix for the error:
> 
> ```
> ERROR: netlink XFRM_MSG_UPDPOLICY response for flow eroute_connection add included errno 22: Invalid argument
> ```
> 
> and updated ikev2-oe-09-transport-ipv6. Just note that problems such as #683 still exist.

On my end, it's not that IPv4 and IPv6 can't coexist, it's that IPv4 standalone works but IPv6 standalone doesn't.

`
Oct 22 14:58:30 node1.domain.tld pluto[10198]: EXPECTATION FAILED: selector_type(dst) == child_afi (bare_kernel_policy() +300 /programs/pluto/kernel.c)
Oct 22 14:58:30 node1.domain.tld pluto[10198]: ERROR: "private#2a01:a0e:5c2:3780:5054::/80": kernel: xfrm XFRM_MSG_UPDPOLICY %trap(ipsec) response for flow (out): Invalid argument (errno 22)

`

**Comment by rnhmjoj** [comment] 2024-04-20 09:58
I can confirm the problem is with IPv6 alone and still there in libreswan 4.15.
To reproduce try:
```
$ ipsec letsencrypt --client
$ echo "::/0" > /etc/ipsec.d/policies/private-or-clear
$ ipsec restart
```
And check the pluto log:
```
EXPECTATION FAILED: selector_type(dst) == child_afi (bare_kernel_policy() +300 /programs/pluto/kernel.c)
ERROR: "private-or-clear#::/0": kernel: xfrm XFRM_MSG_UPDPOLICY %trap(ipsec) response for flow (out): Invalid argument (errno 22)
```

**Comment by rnhmjoj** [comment] 2024-05-01 16:31
Just tested again on 5.0, the issue appears to be finally solved.
There are still some more issues with the `oe-letsencrypt-client.conf`, though.
