### ISSUE TITLE
IPsec/XAuth reusing lease for multiple clients behind same NAT

### ISSUE THREAD

**Issue by MikeLund** [libreswan/libreswan#166] opened 2018-02-12 15:01 UTC
Hi, I've set up an IPsec/XAuth VPN using https://github.com/hwdsl2/setup-ipsec-vpn/issues/314#issuecomment-364926219

Problem is: when two users connect from behind the same NAT, the first client's networking stops working. My guess on the cause of this is what I've named this issue: clients that are behind the same NAT are given same the same VPN IP lease.

In my setup, it's an Android 7.0 client and a macOS High Sierra client. Libreswan version: `Version Libreswan 3.23 XFRM(netkey) KLIPS FORK PTHREAD_SETSCHEDPRIO NSS SYSTEMD_WATCHDOG LABELED_IPSEC LIBCAP_NG XAUTH_PAM NETWORKMANAGER CURL(non-NSS)`
/etc/ipsec.conf:
```
version 2.0

config setup
  virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.42.0/24,%v4:!192.168.43.0/24
  protostack=netkey
  nhelpers=0
  interfaces=%defaultroute
  uniqueids=no

conn shared
  left=%defaultroute
  leftid=94.x.x.222
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024,aes256-sha2_512
  phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2,aes256-sha2_512
  sha2-truncbug=no

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  phase2=esp
  also=shared

conn xauth-psk
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns="8.8.4.4, 8.8.8.8"
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  ikev2=never
  cisco-unity=yes
  also=shared
```

Events from auth.log (202.x.x.111 is the NAT'd clients, 94.x.x.222 is VPN server's IP):
```
# First I connect with Android 7.0 client

Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: responding to Main Mode from unknown peer 202.x.x.111 on port 500
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: STATE_MAIN_R1: sent MR1, expecting MI2
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: STATE_MAIN_R2: sent MR2, expecting MI3
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: Peer ID is ID_IPV4_ADDR: '192.168.143.183'
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP1024}
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Feb 12 17:34:03 ru pluto[5327]: | ISAKMP Notification Payload
Feb 12 17:34:03 ru pluto[5327]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: received and ignored informational message
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: Ignoring NUL at end of XAUTH User Password (Android Issue 36879?)
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: XAUTH: password file authentication method requested to authenticate user 'mobile'
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: XAUTH: password file (/etc/ipsec.d/passwd) open.
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: XAUTH: success user(mobile:xauth-psk)
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: XAUTH: #229: completed for user 'mobile' with status SUCCESSS
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: XAUTH: User mobile: Authentication Successful
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: XAUTH: xauth_inR1(STF_OK)
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP1024}
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: modecfg_inR0(STF_OK)
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP1024}
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #229: the peer proposed: 0.0.0.0/0:0/0 -> 192.168.43.10/32:0/0
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #230: responding to Quick Mode proposal {msgid:4f65cc85}
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #230:     us: 0.0.0.0/0===94.x.x.222[MS+XS+S=C]
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #230:   them: 202.x.x.111[+MC+XC+S=C]===192.168.43.10/32
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #230: keeping refhim=0 during rekey
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #230: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>0x029110e1 <0xff30b449 xfrm=AES_CBC_256-HMAC_SHA2_256_128 NATOA=none NATD=202.x.x.111:14844 DPD=active username=mobile}
Feb 12 17:34:03 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #230: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x029110e1 <0xff30b449 xfrm=AES_CBC_256-HMAC_SHA2_256_128 NATOA=none NATD=202.x.x.111:14844 DPD=active username=mobile}

# Now I connect with macOS client
Feb 12 17:34:17 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: responding to Main Mode from unknown peer 202.x.x.111 on port 46
Feb 12 17:34:17 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: STATE_MAIN_R1: sent MR1, expecting MI2
Feb 12 17:34:17 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: STATE_MAIN_R2: sent MR2, expecting MI3
Feb 12 17:34:17 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Feb 12 17:34:17 ru pluto[5327]: | ISAKMP Notification Payload
Feb 12 17:34:17 ru pluto[5327]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Feb 12 17:34:17 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: Peer ID is ID_IPV4_ADDR: '192.168.143.190'
Feb 12 17:34:17 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP2048}
Feb 12 17:34:17 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
Feb 12 17:34:17 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: XAUTH: password file authentication method requested to authenticate user 'macos'
Feb 12 17:34:17 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: XAUTH: password file (/etc/ipsec.d/passwd) open.
Feb 12 17:34:17 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: XAUTH: success user(macos:xauth-psk)
Feb 12 17:34:17 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: XAUTH: #231: completed for user 'macos' with status SUCCESSS
Feb 12 17:34:17 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: XAUTH: User macos: Authentication Successful
Feb 12 17:34:18 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: XAUTH: xauth_inR1(STF_OK)
Feb 12 17:34:18 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP2048}
Feb 12 17:34:18 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: modecfg_inR0(STF_OK)
Feb 12 17:34:18 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP2048}
Feb 12 17:34:18 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #231: the peer proposed: 0.0.0.0/0:0/0 -> 192.168.43.10/32:0/0
Feb 12 17:34:18 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #232: responding to Quick Mode proposal {msgid:4394c172}
Feb 12 17:34:18 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #232:     us: 0.0.0.0/0===94.x.x.222[MS+XS+S=C]
Feb 12 17:34:18 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #232:   them: 202.x.x.111[+MC+XC+S=C]===192.168.43.10/32
Feb 12 17:34:18 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #232: keeping refhim=0 during rekey
Feb 12 17:34:18 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #232: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>0x0a6c512d <0xfac6b727 xfrm=AES_CBC_256-HMAC_SHA1_96 NATOA=none NATD=202.x.x.111:4500 DPD=active username=macos}
Feb 12 17:34:18 ru pluto[5327]: "xauth-psk"[10] 202.x.x.111 #232: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x0a6c512d <0xfac6b727 xfrm=AES_CBC_256-HMAC_SHA1_96 NATOA=none NATD=202.x.x.111:4500 DPD=active username=macos}
```

Now that both are connected, see trafficstatus:
```
:~# ipsec whack --trafficstatus
006 #228: "xauth-psk"[10] 202.x.x.111, username=mobile, type=ESP, add_time=1518445965, inBytes=32216, outBytes=163708, lease=192.168.43.10/32
006 #232: "xauth-psk"[10] 202.x.x.111, username=macos, type=ESP, add_time=0, inBytes=98529, outBytes=145916, lease=192.168.43.10/32
```
See how both were given same right-lease.

Just to double-check that I'm not crazy, if I connect from outside NAT (eg on 4G), I get a proper unique lease for the mobile client:
```
:~# ipsec whack --trafficstatus
006 #232: "xauth-psk"[10] 202.x.x.111, username=macos, type=ESP, add_time=1518446058, inBytes=207312, outBytes=451325, lease=192.168.43.10/32
006 #234: "xauth-psk"[11] 77.x.x.56, username=mobile, type=ESP, add_time=1518446090, inBytes=1316, outBytes=2597, lease=192.168.43.13/32
```

Hope this is enough information, and I haven't just misconfigured something. Thank you!

**Comment by letoams** [comment] 2018-02-12 15:19
On Mon, 12 Feb 2018, MikeLund wrote:

> Hi, I've set up an IPsec/XAuth VPN using hwdsl2/setup-ipsec-vpn#314 (comment)
> 
> Problem is: when two users connect from behind the same NAT, the first client's networking stops working. My guess on the
> cause of this is what I've named this issue: clients that are behind the same NAT are given same the same VPN IP lease.

That is a known bug in the addresspool code when using authby=secret
where all clients either share the same ID. You would likely get a
different ID, if you configured the clients to use their (native) IP
as ID (which often is the default when using PSK). While that works
a little better, you still run into an issue with two clients behind
different NAT's re-using the same pre-NAT IP.

We hope to address this in libreswan 3.24.

Note if you use raw rsa keys or certifiates, all your clients will have
unique IDs and you won't have this problem. It is specific to
authby=secret

The underlying reason is that we are trying to hand the same lease back
to a re-connecting client so its open connections have a chance of
surviving on reconnect (eg via mobike when you switch between LTE/wifi).
Therefor, using unique ids is always preferred.

So even if we fix this issue, your authby=secret clients would just
always have to be given a new lease, since we cannot distinguish
between a reconnecting client and a new one if they share the same ID.

Paul

**Comment by zzgfw** [comment] 2018-05-16 10:16
Is there any news?

**Comment by letoams** [comment] 2018-05-16 12:53
A fix was pushed in git master. Will be part of 3.24

**Comment by zzgfw** [comment] 2018-05-17 04:31
Got it. Thx!

2018-05-16 20:53 GMT+08:00 Paul Wouters (libreswan) <
notifications@github.com>:

> A fix was pushed in git master. Will be part of 3.24
>
> Sent from my iPhone
>

**Comment by SystemDisc** [comment] 2018-05-19 16:02
@letoams Do you have an ETA for the 3.24 release? I'm very interested in this fix.

**Comment by bunkbail** [comment] 2018-05-27 10:27
Any news for this fix?

**Comment by letoams** [comment] 2018-06-02 03:09
On Sun, 27 May 2018, Nabil Danial wrote:

> Subject: Re: [libreswan/libreswan] IPsec/XAuth reusing lease for multiple
>     clients behind same NAT (#166)
> Any news for this fix?

I uploaded 3.24rc5 to download.libreswan.org/development/

It should appear within the hour on all mirrors.

Paul

**Comment by hwdsl2** [comment] 2018-06-05 09:00
@letoams I tested Libreswan 3.24rc5 and found that although this issue seems fixed (each client now gets a different IP), connecting multiple IPsec/XAuth clients simultaneously from behind the same NAT still does NOT work, i.e. clients "kick each other off", newly connected client will make any previously connected client no longer send traffic.

Tested again using Libreswan 3.22 and it worked without issues with that version. I think some changes from 3.22 -> 3.23 broke this functionality. Can you please look into it? Thank you!

**Comment by hwdsl2** [comment] 2018-06-06 02:40
@HughR @cagney @antonyantony @bleve Pinging the Libreswan team... Can you please look further into this issue (see my latest comment above). Multiple IPsec/XAuth clients from behind the same NAT was working in Libreswan 3.22, but is broken in 3.23 through 3.24rc5. Thank you!

**Comment by letoams** [comment] 2018-06-06 04:31
I am looking into this to ensure a fix goes into 3.24

**Comment by hwdsl2** [comment] 2018-06-06 05:31
Thank you @letoams !

**Comment by hwdsl2** [comment] 2018-06-30 04:30
Unfortunately Libreswan 3.25 did NOT fix the multiple IPsec/XAuth VPN clients behind the same NAT issue. Was working fine in 3.22 as mentioned in my comment above. To be clear, the issue reported by the OP (reusing lease) were fixed, but multiple clients still do not work.

To reproduce, connect multiple IPsec/XAuth VPN clients from behind the same NAT (e.g. home router) to the same Libreswan VPN server. I used a MacBook and an iPhone to connect. After the 2nd client connects, under 3.25, both clients would lose their Internet connection. On the other hand, under Libreswan 3.22 both clients continue to have working Internet connections through the VPN server.

Hope that this can be addressed in 3.26. Thanks!

**Comment by letoams** [comment] 2018-07-02 15:30
On Fri, 29 Jun 2018, Lin Song wrote:

> Unfortunately Libreswan 3.25 did NOT fix the multiple IPsec/XAuth VPN clients behind the same NAT issue. Was working fine
> in 3.22 as mentioned in my comment above. To be clear, the issue reported by the OP (reusing lease) were fixed, but
> multiple clients still do not work.

I am a little confused. Because in 3.25 we never hand out the same lease
to connections with authby=secret which you say you are using. Can you
give us a plutodebug=all log of two clients connecting ?

Paul

**Comment by hwdsl2** [comment] 2018-07-02 15:32
Will do. Do you have an email address to which I can send the logs?

**Comment by letoams** [comment] 2018-07-02 15:34
On Mon, 2 Jul 2018, Lin Song wrote:

> Will do. Do you have an email address to which I can send the logs?

paul@nohats.ca

Paul

**Comment by hwdsl2** [comment] 2018-07-10 17:20
@letoams I sent the logs to your inbox on July 2nd. Please check. Thanks!

**Comment by AlexeySemigradsky** [comment] 2018-07-17 11:34
Is there any news?

**Comment by SystemDisc** [comment] 2018-07-28 00:16
It would be great if someone could come up with a solution that allows multiple connections behind the same NAT, which does not reuse existing connections and does not disconnect existing clients.

**Comment by linux998** [comment] 2018-08-01 08:25
@hwdsl2 hello  Can you read Chinese?  您好，libreswan 是指安装在VPN服务器上的软件吗？ 
我的服务器好像没有安装这个软件也能用，您知道是什么回事吗？

**Comment by GabLeRoux** [comment] 2018-08-20 20:42
@letoams any news on this? or is there a way we can help? I'm hitting this exact same issue for windows users using  and I have everything setup to reproduce this. I only tried with Libreswan 3.22.

I'm using https://github.com/hwdsl2/setup-ipsec-vpn project and there are several issues pointing to this one. :v:

**Comment by letoams** [comment] 2018-08-21 03:07
I've done some testing today and oddly enough get a different issue. Despite authby=secret, it still ends up using the same lease IP for both clients, because c->spd.that.client.addr is the same for both (the IP of the NAT router). I wonder why some are seeing a different lease IP yet then still no traffic flow.

The problem caused here that I see is that you end up with two valid sets of two states (in ip xfrm state) yet there is only one 3 state policy that matches the last set of states (in ip xfrm policy)

Continuing this issue tomorrow

**Comment by letoams** [comment] 2018-08-28 19:50
On Mon, 20 Aug 2018, Gabriel Le Breton wrote:

> @letoams any news on this? or is there a way we can help? I'm hitting this exact same issue for windows users
> using and I have everything setup to reproduce this. I only tried with Libreswan 3.22.

I pushed one fix into git master that should resolve the lease ip re-use
issue. But I'm not sure it will solve all your issues. If you can
verify, please do.

Paul

**Comment by letoams** [comment] 2018-09-18 01:51
note libreswan 3.26 was released that addresses the issue related to bad lease ip re-use. Please re-open this bug if you see any issues

**Closed by letoams** 2018-09-18 01:51 UTC
