### ISSUE TITLE
ip xfrm policy won't delete after an IKEv2 connect close

### ISSUE THREAD

**Issue by MyOzCam** [libreswan/libreswan#618] opened 2022-01-21 08:49 UTC
ip xfrm policy won't be delete after an IKEv2 connection close. related to #541 

Tried "ip xfrm policy ls" to shown policy after a connection established.

```
 _src 0.0.0.0/0 dst 192.168.XXX.BBB/32 
 	dir out priority 1769664 ptype main 
 	tmpl src 192.168.XXX.AAA dst XXX.XXX.XXX.XXX
 		proto esp reqid 16397 mode tunnel
 	if_id 0x1
 src 192.168.XXX.BBB//32 dst 0.0.0.0/0 
 	dir fwd priority 1769664 ptype main 
 	tmpl src XXX.XXX.XXX.XXX dst 192.168.XXX.AAA
 		proto esp reqid 16397 mode tunnel
 	if_id 0x1
 src 192.168.XXX.BBB/32 dst 0.0.0.0/0 
 	dir in priority 1769664 ptype main 
 	tmpl src XXX.XXX.XXX.XXX dst 192.168.XXX.AAA
 		proto esp reqid 16397 mode tunnel
 	if_id 0x1_
```

After disconnect, "ip xfrm policy ls" show 2 policies remain

```
_src 192.168.XXX.BBB//32 dst 0.0.0.0/0 
	dir fwd priority 1769664 ptype main 
	tmpl src XXX.XXX.XXX.XXX dst 192.168.XXX.AAA
		proto esp reqid 16397 mode tunnel
	if_id 0x1
src 192.168.XXX.BBB/32 dst 0.0.0.0/0 
	dir in priority 1769664 ptype main 
	tmpl src XXX.XXX.XXX.XXX dst 192.168.XXX.AAA
		proto esp reqid 16397 mode tunnel
	if_id 0x1_
```

And pluto log show error as below:
`_ERROR: "ikev2-cp"[2] XXX.XXX.XXX.XXX #2: kernel: xfrm XFRM_MSG_DELPOLICYdelete(UNUSED) response for flow (in): No such file or directory (errno 2)_`

I am using ipsec_interface=yes so there are if_id 0x1.

To remove a policy with if_id, we have to specify the if_id as well in command line as follows:
```
ip xfrm policy delete dir fwd src 192.168.XXX.BBB/32 dst 0.0.0.0/0 if_id 0x1
ip xfrm policy delete dir in src 192.168.XXX.BBB/32 dst 0.0.0.0/0 if_id 0x1_
```

Otherwise, same error as shown
`_RTNETLINK answers: No such file or directory_`

I suspect when current (or even previous) libreswan remove a policy that is bonded to xfrm interface, it specifies only the SELECTOR as src/dst without the if_id.

**Comment by MyOzCam** [comment] 2022-01-21 11:19
Further log from kernel regarding POLICY DELETE:
Jan 21 12:35:45 localhost pluto[2058]: | kernel: raw_policy() DELETE_INBOUND REPORT_NO_INBOUND teardown_half_ipsec_sa() teardown inbound Child SA 192.168.XXX.AAA/32-ALL-ALL-0.0.0.0/0 shunt_policy=UNSET encap=<null> lifetime=0s priority=1769664 sa_marks=o:0/0,i:0/0 **xfrm_if_id=0** sec_label=
Jan 21 12:35:45 localhost pluto[2058]: | kernel: raw_policy() DELETE_OUTBOUND THIS_IS_NOT_INBOUND bare_policy_op() outbound shunt for unrouting connection 0.0.0.0/0-ALL-ALL-192.168.XXX.AAA/32 shunt_policy=NONE encap=<null> lifetime=0s priority=1769665 sa_marks=o:0/0,i:0/0 **xfrm_if_id=1** sec_label=
Jan 21 12:35:45 localhost pluto[2058]: | kernel: raw_policy() DELETE_INBOUND EXPECT_NO_INBOUND bare_policy_op() inbound shunt for unrouting connection 192.168.XXX.AAA/32-ALL-ALL-0.0.0.0/0 shunt_policy=NONE encap=<null> lifetime=0s priority=1769665 sa_marks=o:0/0,i:0/0 **xfrm_if_id=0** sec_label=

For unknown reason, when deleting the OUTBOUND policy, system explicit the xfrm_if_id=1 but when deleting the INBOUND polices (FWD/IN), only xfrm_if_id=0 is specified and that is wrong.

**Comment by letoams** [comment] 2022-01-21 21:18
On Fri, 21 Jan 2022, MyOzCam wrote:

> For unknown reason, when deleting the OUTBOUND policy, system explicit the xfrm_if_id=1 but when deleting the INBOUND polices
> (FWD/IN), only xfrm_if_id=0 is specified and that is wrong.

Thanks for the report. I've reproduced this in testcase ikev2-xfrm-02.

Hopefully, this should be fixed soon.

**Comment by cagney** [comment] 2022-01-22 02:53
it looks like both:

- sa_marks
- xfrm_if_id

are needed (but many calls pass in only one, or none).  I guess we try bundling them up and then always passing them in.

**Closed** 2022-01-22 14:13 UTC

**Comment by letoams** [comment] 2022-01-22 15:59
That’s exactly what kernel_sa is for ?

Sent using a virtual keyboard on a phone

**Comment by cagney** [comment] 2022-01-22 16:57
struct kernel_sa (it could easily be called kernel_state) tries to describe a single `ip xfrm state`
this code is dealing with the convoluted mess known as `ip xfrm policy`
