### ISSUE TITLE
Libreswan 4.6 error related to XFRM_MSG_DELPOLICY

### ISSUE THREAD

**Issue by hwdsl2** [libreswan/libreswan#612] opened 2022-01-12 05:53 UTC
Possible regression in Libreswan 4.6. When an IKEv2 connection is disconnected by the VPN client (tested with iOS 15), the following errors appear in the Libreswan logs on the server. Libreswan 4.5 does not have this problem. Possibly related: #542.

```
"ikev2-cp"[3] X.X.X.X: kernel: xfrm XFRM_MSG_DELPOLICY for flow %discard(discard)(in) encountered unexpected policy
ERROR: "ikev2-cp"[3] X.X.X.X #6: kernel: xfrm XFRM_MSG_DELPOLICYdelete(UNUSED) response for flow (in): No such file or directory (errno 2)
"ikev2-cp"[3] X.X.X.X #6: raw_policy in teardown_half_ipsec_sa() failed to delete inbound
"ikev2-cp"[3] X.X.X.X #5: deleting state (STATE_V2_ESTABLISHED_IKE_SA) aged 7.233876s and NOT sending notification
"ikev2-cp"[3] X.X.X.X: deleting connection instance with peer X.X.X.X {isakmp=#0/ipsec=#0}
```

**Comment by cagney** [comment] 2022-01-12 14:48
Was the Child SA fully installed, and is there a policy lingering?

4.6 fixed a bug where a policy with a security label wasn't always deleted.  Since the bug was hidden by code suppressing policy-delete errors, that too was changed.  Consequently, what we might be seeing is a regression, a long standing problem now exposed, or even a case where the delete shouldn't have happened.

**Comment by hwdsl2** [comment] 2022-01-12 15:22
@cagney Thanks for the quick response. Do you know how to check whether the child SA is fully installed and/or policy lingering?

Steps to reproduce the issue:
1. Set up the IPsec VPN server using the quick start script in my repo [1]. I think you can pick any OS from the docs, such as Debian 11.
2. Import the generated IKEv2 configuration (e.g. vpnclient.mobileconfig) into your device. Instructions at [2]. I tested using iOS 15, but this issue is possibly not limited to iOS clients.
3. Connect the VPN, then disconnect.
4. Check the logs on the VPN server using e.g. `grep pluto /var/log/auth.log`. You should see the errors I mentioned in this issue.

Even though this error appears, in `ipsec status` it shows no active connections after the client disconnects. So perhaps this error might be harmless?

FYI @paulwouters

[1] https://github.com/hwdsl2/setup-ipsec-vpn#quick-start
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#configure-ikev2-vpn-clients

**Comment by cagney** [comment] 2022-01-12 16:14
The logs would show something like "established Child SA".

Any problem will be between libreswan and the kernel.   Run `ipsec look` (or, on linux, just `ip xfrm policy`) before during and after the exchanges.  After the exchange the policies should be all gone.

**Comment by hwdsl2** [comment] 2022-01-13 05:15
Findings:
1. The "established Child SA" did appear in the logs.
2. After the IKEv2 VPN client (iOS 15 in this case) disconnects, all XFRM states and policies in the output of `ipsec look` disappeared as expected. In addition, all added XFRM policies in the output of `ip xfrm policy` also disappeared as expected.

So, despite the errors shown in my first post, which are displayed each time the IKEv2 client disconnects, XFRM states and policies appear to be cleaned up correctly.

**Comment by cagney** [comment] 2022-01-19 00:38
If possible, on the server, could you enable debugging (plutodebug=all)?
I'm only interested in the lines prefixed with:
```
  | kernel:
```
that lead into the error (to narrow it even further its the raw_policy() calls adding and deleting policies).

**Comment by hwdsl2** [comment] 2022-01-19 04:17
@cagney Please see below for the (redacted) logs you requested. This is the log when an IKEv2 client's disconnects.

```
| kernel: get_sa_info esp.abcdefg@1.2.3.4
| kernel: get_sa_info esp.bcdefghi@172.17.X.X
| kernel: running updown command "ipsec _updown" for verb down
| kernel: command executing down-client
| kernel: get_sa_info esp.abcdefg@1.2.3.4
| kernel: get_sa_info esp.bcdefghi@172.17.X.X
| kernel: bare_policy_op() DELETE_OUTBOUND EXPECT_NO_INBOUND unrouting connection "ikev2-cp"[1] 1.2.3.4 rt_kind 'unrouted' shunt_policy=NONE 0.0.0.0/0-ALL->192.168.43.10/32 (config)sec_label=
| kernel: raw_policy() DELETE_OUTBOUND THIS_IS_NOT_INBOUND bare_policy_op() outbound shunt for unrouting connection 0.0.0.0/0-ALL-ALL-192.168.43.10/32 shunt_policy=NONE encap=<null> lifetime=0s priority=XXXX sa_marks=o:0/0,i:0/0 xfrm_if_id=0 sec_label=
| kernel: policy: result=success
| kernel: raw_policy() DELETE_INBOUND EXPECT_NO_INBOUND bare_policy_op() inbound shunt for unrouting connection 192.168.43.10/32-ALL-ALL-0.0.0.0/0 shunt_policy=NONE encap=<null> lifetime=0s priority=XXXX sa_marks=o:0/0,i:0/0 xfrm_if_id=0 sec_label=
| kernel: policy: result=success
| kernel: running updown command "ipsec _updown" for verb unroute
| kernel: command executing unroute-client
| kernel: deleting spi 172.17.X.X -> esp.abcdefg@1.2.3.4
| kernel: raw_policy() DELETE_INBOUND REPORT_NO_INBOUND teardown_half_ipsec_sa() teardown inbound Child SA 192.168.43.10/32-ALL-ALL-0.0.0.0/0 shunt_policy=UNSET encap=<null> lifetime=0s priority=XXXX sa_marks=o:0/0,i:0/0 xfrm_if_id=0 sec_label=
| kernel: policy: result=failed
| kernel: deleting spi 1.2.3.4 -> esp.bcdefghi@172.17.X.X
```

**Comment by hwdsl2** [comment] 2022-01-19 04:31
To add to my previous response... For Windows IKEv2 clients, there's also an unexpected "established IKE SA" log message when the IKEv2 client *disconnects*. This is in addition to the error in my first post, not sure if related. See the highlighted log line below. iOS IKEv2 clients do NOT trigger this log line when disconnecting.

```
"ikev2-cp"[1] 1.2.3.4: kernel: xfrm XFRM_MSG_DELPOLICY for flow %discard(discard)(in) encountered unexpected policy
ERROR: "ikev2-cp"[1] 1.2.3.4 #2: kernel: xfrm XFRM_MSG_DELPOLICYdelete(UNUSED) response for flow (in): No such file or directory (errno 2)
"ikev2-cp"[1] 1.2.3.4 #2: raw_policy in teardown_half_ipsec_sa() failed to delete inbound
-->  "ikev2-cp"[1] 1.2.3.4 #1: established IKE SA  <--
"ikev2-cp"[1] 1.2.3.4 #1: deleting state (STATE_V2_ESTABLISHED_IKE_SA) aged 8.850266s and NOT sending notification
"ikev2-cp"[1] 1.2.3.4: deleting connection instance with peer 1.2.3.4 {isakmp=#0/ipsec=#0}
```

**Comment by MyOzCam** [comment] 2022-01-20 16:00
> Findings:
> 
> 1. The "established Child SA" did appear in the logs.
> 2. After the IKEv2 VPN client (iOS 15 in this case) disconnects, all XFRM states and policies in the output of `ipsec look` disappeared as expected. In addition, all added XFRM policies in the output of `ip xfrm policy` also disappeared as expected.
> 
> So, despite the errors shown in my first post, which are displayed each time the IKEv2 client disconnects, XFRM states and policies appear to be cleaned up correctly.

I have gotten same error but policies did cleaned up correctly. Only 1 outbound policy removed and 2 inbound polices remain.

Log:
 | kernel: raw_policy() DELETE_INBOUND REPORT_NO_INBOUND teardown_half_ipsec_sa() teardown inbound Child SA 192.168.XX.AA/32-ALL-ALL-0.0.0.0/0 shunt_policy=UNSET encap=<null> lifetime=0s priority=1769664 sa_marks=o:0/0,i:0/0 xfrm_if_id=0 sec_label=
 | xfrm_raw_policy() policy=delete(UNUSED)/3 dir=0
 | xfrm_raw_policy() using family IPv4 (2)
 | xfrm_raw_policy() ignoring xfrm_user_tmpl because NULL, policy=3 op=10
 | xfrm: sendrecv_xfrm_msg() sending 20
 ERROR: "ikev2-cp"[4] 161.81.XXX.XXX #4: kernel: xfrm XFRM_MSG_DELPOLICYdelete(UNUSED) response for flow (in): No such file or directory (errno 2)
 | xfrm: xfrm_raw_policy() deleting policy forward (even when there may not be one)
 | xfrm: sendrecv_xfrm_msg() sending 20
 | kernel: policy: result=failed
 "ikev2-cp"[4] 161.81.XXX.XXX #4: raw_policy in teardown_half_ipsec_sa() failed to delete inbound
 | kernel: deleting spi 161.81.XXX.XXX -> esp.6e19ebad@192.168.XX.BB
 | XFRM: deleting IPsec SA with reqid 0

**Comment by cagney** [comment] 2022-01-20 19:01
@MyOzCam please file a new bug.

**Comment by cagney** [comment] 2022-01-22 02:58
#618 is not related, hopefully that bug is just a case of missing parameters.

**Comment by cagney** [comment] 2022-01-22 03:13
> "established IKE SA" log message when the IKEv2 client *disconnects*
This misleading log line from the state machine indicating a transition finished.

So we have these two calls, but we only need one:

- bare_policy_op() outbound shunt for unrouting connection
- teardown_half_ipsec_sa() teardown inbound Child SA

I tend to think that the second is more correct.

(as a work-around, the second call's warning could be suppressed).

**Comment by cagney** [comment] 2022-03-31 18:04
It turns out that the call from `teardown_half_ipsec_sa()` is wrong. `teardown_ipsec_sa()`:

- goes through the spd_routes looking for kernel policies that need updating/deleting
- calls teardown_half_ipsec_sa() to delete the kernel states

but then `teardown_half_ipsec_sa()` also deletes the incoming policy.  This call, which pre-dates history, should be merged into teardown_ipsec_sa()

**Comment by cagney** [comment] 2022-04-07 13:51
Should be fixed.

**Closed by cagney** 2022-04-07 13:51 UTC
Labels: regression, xfrm
