### ISSUE TITLE
Python error in ipsec verify

### ISSUE THREAD

**Issue by sebelk** [libreswan/libreswan#56] opened 2016-04-28 17:50 UTC
I have installed libreswan-3.17-1.fc23.x86_64,

And it outputs:

 ```
Pluto ipsec.secret syntax                        Traceback (most recent call last):
  File "/usr/libexec/ipsec/verify", line 477, in <module>
    main()
  File "/usr/libexec/ipsec/verify", line 466, in main
    plutocheck()
  File "/usr/libexec/ipsec/verify", line 121, in plutocheck
    ipsecsecretcheck()
  File "/usr/libexec/ipsec/verify", line 375, in ipsecsecretcheck
    output = output.decode(prefencoding)
AttributeError: 'str' object has no attribute 'decode'
```

Python version is Python 3.4.3

Is this a bug? if it is not how can I fix it?

Thanks in advance

**Comment by letoams** [comment] 2016-04-30 17:01
I cannot seem to reproduce this error. It might be specific to your secrets file(s)

You  should not give your secrets to me or post them publicly, but perhaps you can investigate by removing/adding to see what entry is causing this. And then give me a censored or fake entry that shows the same problem?

**Comment by sebelk** [comment] 2016-05-01 00:39
I have en entry, but log it told me:

> "/etc/ipsec.d/windows.secrets" line 1: WARNING: The :RSA secrets entries for X.509 certificates are no longer needed

So, I removed the line... but the error of ipsec verify stays there...

Thanks in advance!

**Comment by letoams** [comment] 2016-05-05 18:01
again, i dont have enough information to reproduce this. Can you somehow give me your ipsec.secrets with the entries mangles so i dont actually receive any secrets?

**Comment by gsra99** [comment] 2016-08-07 14:07
Hi I am having the same issue. Was there a solution for this. I have libreswan version 3.17. My /etc/ipsec.d/x.secrets contains:
%any: PSK "***my_password***"
My password has been removed.

**Comment by gsra99** [comment] 2016-08-07 14:08
I have python 3.4 as well

**Comment by letoams** [comment] 2016-08-07 16:04
it works for me on python 2.7 and 3.5. I do not have a system with python 3.4 to test against.

**Comment by kirill-krokodil** [comment] 2016-10-07 11:39
hello, again @letoams !
seems like this bug is pretty common too:
https://ask.fedoraproject.org/en/question/86294/cant-connect-to-l2tpipsec-vpn-server/
some nice guy already discovered issue and offered some solution for libreswan library.

maybe you can check it?
thanks anyway!

**Comment by letoams** [comment] 2016-10-07 16:42
I just pushed the fix for this. Should be in the next release (3.19)

Thanks!

**Closed by letoams** 2016-10-07 16:42 UTC
