### ISSUE TITLE
SA is not created for for all configured subnets

### ISSUE THREAD

**Issue by omerd12** [libreswan/libreswan#470] opened 2021-07-04 13:52 UTC
[pluto.log.tar.gz](https://github.com/libreswan/libreswan/files/6759852/pluto.log.tar.gz)
We are experiencing problems with setups which configure multiple subnets. For example:
**On Gateway A:**
conn ams-site@1ee81166473142158906f652671d6e8a@MzQuMTQxLjE4MS42Ng==@34.141.181.66@198.211.126.194@@Customer
    type=tunnel
    auto=start
    left=10.240.0.76
    leftid=34.91.104.123
    leftsubnet=192.168.1.0/24
    right=34.147.19.185
    rightid=34.147.19.185 rightsubnets=192.168.100.0/24,192.168.101.0/24,192.168.102.0/24,192.168.103.0/24,192.168.104.0/24,192.168.105.0/24,192.168.106.0/24,192.168.107.0/24,192.168.108.0/24,192.168.109.0/24,192.168.110.0/24,192.168.111.0/24,192.168.112.0/24,192.168.113.0/24,192.168.114.0/24,192.168.115.0/24
    authby=secret
    ike=aes128-sha1;modp1536
    aggrmode=no
    ikev2=insist
    ikelifetime=3600
    phase2alg=aes_gcm128-null;modp1536
    pfs=yes
    salifetime=3600
    rekeymargin=9m
    dpddelay=3
    dpdtimeout=5
    dpdaction=restart
    retransmit-timeout=60
    narrowing=no

**On Gateway B:**
conn ams-site@1ee81166473142158906f652671d6e8a@MzQuMTQxLjE4MS42Ng==@34.141.181.66@198.211.126.194@@Customer
    type=tunnel
    auto=start
    right=34.91.104.123
    rightid=34.91.104.123
    rightsubnet=192.168.1.0/24
    left=10.240.0.77
    leftid=34.147.19.185
    leftsubnets=192.168.112.0/24,192.168.113.0/24,192.168.114.0/24,192.168.115.0/24
    authby=secret
    ike=aes128-sha1;modp1536
    aggrmode=no
    ikev2=insist
    ikelifetime=3600
    phase2alg=aes_gcm128-null;modp1536
    pfs=yes
    salifetime=3600
    rekeymargin=9m
    dpddelay=3
    dpdtimeout=5
    dpdaction=restart
    retransmit-timeout=60
    narrowing=no

Occasionly, after restarting the connection (or deleting and re-adding the connection) on gateway A, not all the connections for all the subnets are re-created. we see only 2 out of 4 connections are up.

ipsec status output and logs for pluto is attached.
[ipsec_status.txt](https://github.com/libreswan/libreswan/files/6759873/ipsec_status.txt)

**Comment by bleve** [comment] 2021-07-04 14:13
Is mismatch of subnets intentionally done or error? Fix list of subnets to be exactly same on both ends.

**Comment by omerd12** [comment] 2021-07-04 14:39
> Is mismatch of subnets intentionally done or error? Fix list of subnets to be exactly same on both ends.

it is intentional, is it not supported?

**Comment by bleve** [comment] 2021-07-04 17:40
It is a configuration error which should not happen - If your connection is auto=start you shouldn't really have extra subnets.

if your connection is auto=add and remote is always initiating that will work.

**Comment by letoams** [comment] 2021-07-05 01:20
On Sun, 4 Jul 2021, omerd12 wrote:

> We are experiencing problems with setups which configure multiple subnets. For example:

> On Gateway A:
> leftsubnet=192.168.1.0/24
> rightsubnets=192.168.100.0/24,192.168.101.0/24,192.168.102.0/24,192.168.103.0/24,192.168.104.0/24,192.168.105.0/24,192.168.106.0/24,192.168.107.0/24,192.
> 168.108.0/24,192.168.109.0/24,192.168.110.0/24,192.168.111.0/24,192.168.112.0/24,192.168.113.0/24,192.168.114.0/24,192.168.115.0/24

> On Gateway B:
> rightsubnet=192.168.1.0/24
> leftsubnets=192.168.112.0/24,192.168.113.0/24,192.168.114.0/24,192.168.115.0/24

> Occasionly, after restarting the connection (or deleting and re-adding the connection) on gateway A, not all the connections for all the subnets are
> re-created. we see only 2 out of 4 connections are up.

That is a bug we are aware of and working on.

Paul

**Comment by bleve** [comment] 2021-07-05 08:34
Because it won't be fixed in older libreswan versions, change your configs so that tunnels will match to get rid of your problem for now or make sure your end with more tunnels is in auto=add and dpdaction=clear so iwon't initiate tunnel.

Also note your dpd values are very low causing more problmes than you likely want. I'd use something like dpddelay=60, dpdtimeout=70 so short network interruptions won't cause you problems.

**Comment by omerd12** [comment] 2021-07-05 08:56
thank you so much for your help! @bleve @letoams 
Since we don't have full control over both sides of the tunnel, configuration tweaks/fixes might not be 100% suited for us.
Is the bug expected to be resolved soon? we'll be willing to upgrade to a newer version with a fix since it causes us quite a headache from time to time.

**Comment by letoams** [comment] 2021-07-05 11:59
On Mon, 5 Jul 2021, omerd12 wrote:

> Is the bug expected to be resolved soon? we'll be willing to upgrade to a newer version with a fix since it causes us quite a
> headache from time to time.

I do hope to resolve it for the next release (4.5)

Paul

**Comment by paulwouters** [comment] 2021-07-06 20:46
I pushed a partial fix that should only fail the misconfigured subnets. Can you try the current git main code and let us know if this addresses your issue?

**Comment by omerd12** [comment] 2021-07-07 10:39
> I pushed a partial fix that should only fail the misconfigured subnets. Can you try the current git main code and let us know if this addresses your issue?

Thank you! I will try ASAP and let you know

**Comment by omerd12** [comment] 2021-07-07 14:27
I'm trying to build the main git code on a Centos 7 machine, and I'm having problems with the linkage.
something with the USE_DNSSEC I guess.

```
libreswan/programs/pluto/ikev2_ike_sa_init.c:629: undefined reference to `idr_ipseckey_fetch'
ikev2_ike_auth.o: In function `process_v2_IKE_AUTH_request_post_cert_decode':
libreswan/programs/pluto/ikev2_ike_auth.c:801: undefined reference to `idi_ipseckey_fetch'
/root/rpmbuild/BUILD/libreswan-4.5dr1/OBJ.linux.x86_64/lib/libswan/libswan.a(unbound.o): In function `unbound_ctx_config':
libreswan/lib/libswan/unbound.c:63: undefined reference to `ub_ctx_hosts'
libreswan/lib/libswan/unbound.c:85: undefined reference to `ub_ctx_resolvconf'
libreswan/lib/libswan/unbound.c:100: undefined reference to `ub_ctx_set_option'
libreswan/lib/libswan/unbound.c:110: undefined reference to `ub_ctx_set_option'
libreswan/lib/libswan/unbound.c:140: undefined reference to `ub_ctx_add_ta_file'
libreswan/lib/libswan/unbound.c:112: undefined reference to `ub_strerror'
libreswan/lib/libswan/unbound.c:102: undefined reference to `ub_strerror'
libreswan/lib/libswan/unbound.c:89: undefined reference to `ub_strerror'
libreswan/lib/libswan/unbound.c:65: undefined reference to `ub_strerror'
libreswan/lib/libswan/unbound.c:58: undefined reference to `ub_ctx_debuglevel'
libreswan/lib/libswan/unbound.c:161: undefined reference to `ub_ctx_add_ta_file'
libreswan/lib/libswan/unbound.c:163: undefined reference to `ub_strerror'
libreswan/lib/libswan/unbound.c:144: undefined reference to `ub_strerror'
/root/rpmbuild/BUILD/libreswan-4.5dr1/OBJ.linux.x86_64/lib/libswan/libswan.a(unbound.o): In function `unbound_ctx_free':
libreswan/lib/libswan/unbound.c:47: undefined reference to `ub_ctx_delete'
/root/rpmbuild/BUILD/libreswan-4.5dr1/OBJ.linux.x86_64/lib/libswan/libswan.a(unbound.o): In function `unbound_event_init':
libreswan/lib/libswan/unbound.c:207: undefined reference to `ub_ctx_create_event'
/root/rpmbuild/BUILD/libreswan-4.5dr1/OBJ.linux.x86_64/lib/libswan/libswan.a(unbound.o): In function `unbound_sync_init':
libreswan/lib/libswan/unbound.c:224: undefined reference to `ub_ctx_create'
/root/rpmbuild/BUILD/libreswan-4.5dr1/OBJ.linux.x86_64/lib/libswan/libswan.a(unbound.o): In function `unbound_resolve':
libreswan/lib/libswan/unbound.c:247: undefined reference to `ub_resolve'
libreswan/lib/libswan/unbound.c:304: undefined reference to `ub_resolve_free'
libreswan/lib/libswan/unbound.c:270: undefined reference to `ub_resolve_free'
libreswan/lib/libswan/unbound.c:249: undefined reference to `ub_strerror'
libreswan/lib/libswan/unbound.c:258: undefined reference to `ub_resolve_free'
```
I can open a different issue if you prefer

**Comment by letoams** [comment] 2021-07-07 14:29
On Wed, 7 Jul 2021, omerd12 wrote:

> I'm trying to build the main git code on a Centos 7 machine, and I'm having problems with the linkage.
> something with the USE_DNSSEC I guess.

Check packaging/rhel/7/libreswan.spec for the settings you should use.

**Comment by omerd12** [comment] 2021-07-07 17:46
I'm using USE_DNSSEC=false as it should be on CentOS 7. building version 4.4 works fine. it appears to be problematic only in 4.5.
In libreswan/programs/pluto/ikev2_ike_sa_init.c:629 and in libreswan/programs/pluto/ikev2_ike_auth.c:801 there are usages of functions without definition if USE_DNSSEC is false.

**Comment by paulwouters** [comment] 2021-07-07 19:44
I'll have a look

**Comment by paulwouters** [comment] 2021-07-07 19:58
I cannot reproduce that ?
can you do:

rm -rf OBJ*
echo "WERROR_CFLAGS=" > Makefile.inc.local
make install

**Comment by paulwouters** [comment] 2021-07-07 19:58
it worked for me with USE_DNSSEC set to true or false

**Comment by omerd12** [comment] 2021-07-08 09:54
> it worked for me with USE_DNSSEC set to true or false

you are right, my bad. worked after cleaning old OBJ files. 
Thanks for all your help! 
However, after testing with your fix, the issue persists. Out of 4 valid subnets, only 1 connection is up.
I used the same configurations as in my first comment.

**Comment by letoams** [comment] 2021-07-08 11:51
On Thu, 8 Jul 2021, omerd12 wrote:

>       it worked for me with USE_DNSSEC set to true or false
> 
> you are right, my bad. worked after cleaning old OBJ files.
> Thanks for all your help!
> However, after testing with your fix, the issue persists. Out of 4 valid subnets, only 1 connection is up.

Are you sure you are running the new version and not the old one? Did
you build an rpm to update the existing version, or did you run
make install? If the latter, did you remove the rpm?

What's the output of: ipsec pluto --version

If it really is the new version, can you enable plutodebug=tmi in
/etc/ipsec.conf and somehow share the logs?

Paul

**Comment by omerd12** [comment] 2021-07-08 14:13
I built a rpm from the source using libreswan.spec. no previous libreswan version had been installed on the gateway machines.
ipsec pluto --version output:
`Libreswan 4.5dr1 IKEv2 IKEv1 XFRM XFRMI esp-hw-offload FORK PTHREAD_SETSCHEDPRIO GCC_EXCEPTIONS NSS (IPsec profile) (native-PRF) SYSTEMD_WATCHDOG FIPS_BINCHECK LABELED_IPSEC (SELINUX) SECCOMP LIBCAP_NG AUTH_PAM NETWORKMANAGER CURL(non-NSS) LDAP(non-NSS)`

attached logs: 
[pluto.log.tar.gz](https://github.com/libreswan/libreswan/files/6785136/pluto.log.tar.gz)

**Comment by paulwouters** [comment] 2021-07-08 17:00
It looked from the logs that your IKE SA remained up, unlike before. So that looks good.

It is just that ZERO of your subnets seemed to match with the other side, so you have 0 tunnels up ?

**Comment by omerd12** [comment] 2021-07-11 07:40
yes I have 0 tunnels up, sometimes 1 tunnel is up, even though there are 4 matching subnets. If I remove some of the mismatched subnets it works better.

**Comment by letoams** [comment] 2021-07-11 22:40
On Sun, 11 Jul 2021, omerd12 wrote:

> yes I have 0 tunnels up, sometimes 1 tunnel is up, even though there are 4 matching subnets. If I remove some of the mismatched subnets it works better.

If you still see this with our latest git, then it looks like the other
end might have issues on its own - eg if it is also running an older
libreswan ?

But as I said, from the logs it seems none of your tunnels was correctly
accepted, which is really strange.

**Comment by omerd12** [comment] 2021-07-12 09:01
Both ends are running latest git (installed same rpm).
The issue is quite persistent.
If you could please take a look I'd really appreciate it, these are the logs from both ends:
gw1 - 
[gw1-pluto.log-20210712.tar.gz](https://github.com/libreswan/libreswan/files/6800005/gw1-pluto.log-20210712.tar.gz)
configuration:
`conn ams-site@Customer
    type=tunnel
    auto=start
    left=10.240.0.81
    leftid=34.147.18.122
    rightsubnet=192.168.1.0/24
    right=34.90.200.49
    rightid=34.90.200.49
    leftsubnets=192.168.112.0/24,192.168.113.0/24,192.168.114.0/24,192.168.115.0/24
    authby=secret
    ike=aes128-sha1;modp1536
    aggrmode=no
    ikev2=insist
    ikelifetime=3600
    phase2alg=aes_gcm128-null;modp1536
    pfs=yes
    salifetime=3600
    rekeymargin=9m
    dpddelay=3
    dpdtimeout=5
    dpdaction=restart
    retransmit-timeout=60
    narrowing=no`

gw2 - 
[gw2-pluto.log-20210712.tar.gz](https://github.com/libreswan/libreswan/files/6800006/gw2-pluto.log-20210712.tar.gz)
configuration:
`conn ams-site@Customer
    type=tunnel
    auto=start
    left=10.240.0.80
    leftid=34.90.200.49
    leftsubnet=192.168.1.0/24
    right=34.147.18.122
    rightid=34.147.18.122
rightsubnets=192.168.100.0/24,192.168.101.0/24,192.168.102.0/24,192.168.103.0/24,192.168.104.0/24,192.168.105.0/24,192.168.106.0/24,192.168.107.0/24,192.168.108.0/24,192.168.109.0/24,192.168.110.0/24,192.168.111.0/24,192.168.112.0/24,192.168.113.0/24,192.168.114.0/24,192.168.115.0/24
    authby=secret
    ike=aes128-sha1;modp1536
    aggrmode=no
    ikev2=insist
    ikelifetime=3600
    phase2alg=aes_gcm128-null;modp1536
    pfs=yes
    salifetime=3600
    rekeymargin=9m
    dpddelay=3
    dpdtimeout=5
    dpdaction=restart
    retransmit-timeout=60
    narrowing=no`

**Comment by letoams** [comment] 2021-07-12 18:13
On Mon, 12 Jul 2021, omerd12 wrote:

> If you could please take a look I'd really appreciate it, these are the logs from both ends:
> gw1 -
> gw1-pluto.log-20210712.tar.gz
> configuration:
> conn ams-site@Customer type=tunnel auto=start left=10.240.0.81 leftid=34.147.18.122 rightsubnet=192.168.1.0/24 right=34.90.200.49 rightid=34.90.200.49
> leftsubnets=192.168.112.0/24,192.168.113.0/24,192.168.114.0/24,192.168.115.0/24 authby=secret ike=aes128-sha1;modp1536 aggrmode=no ikev2=insist
> ikelifetime=3600 phase2alg=aes_gcm128-null;modp1536 pfs=yes salifetime=3600 rekeymargin=9m dpddelay=3 dpdtimeout=5 dpdaction=restart retransmit-timeout=60
> narrowing=no
> 
> gw2 -
> gw2-pluto.log-20210712.tar.gz
> configuration:
> conn ams-site@Customer type=tunnel auto=start left=10.240.0.80 leftid=34.90.200.49 leftsubnet=192.168.1.0/24 right=34.147.18.122 rightid=34.147.18.122rightsubnets=192.168.100.0/24,192.168.101.0/24,192.168.102.0/24,192.168.103.0/24,192.168.104.0/24,192.168.105.0/24,192.168.106.0/24,192.168.107.0/24,192.
> 168.108.0/24,192.168.109.0/24,192.168.110.0/24,192.168.111.0/24,192.168.112.0/24,192.168.113.0/24,192.168.114.0/24,192.168.115.0/24 authby=secret
> ike=aes128-sha1;modp1536 aggrmode=no ikev2=insist ikelifetime=3600 phase2alg=aes_gcm128-null;modp1536 pfs=yes salifetime=3600 rekeymargin=9m dpddelay=3
> dpdtimeout=5 dpdaction=restart retransmit-timeout=60 narrowing=no

I just noticed both endpoints are behind NAT and using auto=start. Do
both have a portfoward from the NAT device port 4500/4500 to their
internal IP (10.240.0.80 and 10.240.0.81) ?

**Comment by omerd12** [comment] 2021-07-13 07:39
yes, all ports are forwarded to the internal IP.

**Comment by letoams** [comment] 2021-07-13 12:49
I reproduced it again. Seems to happen when there are a larger set of subnets. Will get back to you

**Comment by cagney** [comment] 2021-12-22 19:23
The IKE SA establishes which means it got passed refine_host_connection*(), but then failed with the child in:
```
/*
 * Find the best connection, possibly scribbling on the just
 * instantiated child, possibly instantiating a new connection.
 */
bool v2_process_request_ts_payloads(struct child_sa *child,
				    const struct msg_digest *md)
```
(I'd set debug=all not tmi), in mainline, on the responder, look for the output:
```
	dbg("looking for better host pair");
```
this will be followed by debug logs showing why each connection is rejected.
(mainline is needed, the search strategy changed somewhat)

**Comment by cagney** [comment] 2022-12-24 02:02
Using mainline (i.e., >4.9), please try:
```
leftsubnet=192.168.112.0/24,192.168.113.0/24,192.168.114.0/24,192.168.115.0/24
```
(note, singular, not subnetS=) it will use the new TS code and put everything through a single tunnel.
If there are problems please open a new bug.  It also includes the performance improvements from 4.9 (specifically here, linear searches through long lists of subnets).

**Closed by cagney** 2022-12-24 02:02 UTC
